from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import json


class VisibilityProject(models.Model):
    """Main project tracking AI visibility checks"""
    STATUS_CHOICES = [
        ('setup', 'Setup'),
        ('validating', 'Validating'),
        ('checking', 'Checking Visibility'),
        ('analyzing', 'Analyzing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects')
    name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    company_description = models.TextField()
    area_of_work = models.CharField(max_length=255)
    
    # Generated by AI
    refined_summary = models.TextField(blank=True, null=True)
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='setup')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(blank=True, null=True)
    
    # Impersonation mode
    is_competitor_view = models.BooleanField(default=False)
    competitor_brand_id = models.IntegerField(blank=True, null=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.company_name} - {self.name}"


class Brand(models.Model):
    """Represents the main company being tracked"""
    project = models.OneToOneField(VisibilityProject, on_delete=models.CASCADE, related_name='main_brand')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.name


class Competitor(models.Model):
    """Competitor brands for comparison"""
    project = models.ForeignKey(VisibilityProject, on_delete=models.CASCADE, related_name='competitors')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    is_ai_suggested = models.BooleanField(default=True)
    is_validated = models.BooleanField(default=False)
    
    class Meta:
        unique_together = ['project', 'name']
    
    def __str__(self):
        return f"{self.name} (Competitor)"


class AIModel(models.Model):
    """Available AI models for querying"""
    MODEL_TYPES = [
        ('chatgpt', 'ChatGPT'),
        ('claude', 'Claude'),
        ('gemini', 'Gemini'),
    ]
    
    name = models.CharField(max_length=50, choices=MODEL_TYPES, unique=True)
    display_name = models.CharField(max_length=100)
    weight = models.FloatField(default=1.0)  # Model coverage weight
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.display_name


class Prompt(models.Model):
    """Prompts/queries to test against AI models"""
    project = models.ForeignKey(VisibilityProject, on_delete=models.CASCADE, related_name='prompts')
    text = models.TextField()
    is_ai_generated = models.BooleanField(default=True)
    is_selected = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['created_at']
    
    def __str__(self):
        return self.text[:100]


class ModelSelection(models.Model):
    """Track which models are selected for a project"""
    project = models.ForeignKey(VisibilityProject, on_delete=models.CASCADE, related_name='selected_models')
    model = models.ForeignKey(AIModel, on_delete=models.CASCADE)
    is_selected = models.BooleanField(default=True)
    
    class Meta:
        unique_together = ['project', 'model']


class PromptResponse(models.Model):
    """Raw responses from AI models"""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('success', 'Success'),
        ('failed', 'Failed'),
        ('partial', 'Partial Data'),
    ]
    
    project = models.ForeignKey(VisibilityProject, on_delete=models.CASCADE, related_name='responses')
    prompt = models.ForeignKey(Prompt, on_delete=models.CASCADE, related_name='responses')
    model = models.ForeignKey(AIModel, on_delete=models.CASCADE)
    
    raw_response = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    error_message = models.TextField(blank=True)
    retry_count = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(blank=True, null=True)
    
    class Meta:
        unique_together = ['prompt', 'model']
        ordering = ['created_at']
    
    def __str__(self):
        return f"{self.model.display_name} - {self.prompt.text[:50]}"


class BrandMention(models.Model):
    """Extracted brand mentions from responses"""
    response = models.ForeignKey(PromptResponse, on_delete=models.CASCADE, related_name='mentions')
    brand_name = models.CharField(max_length=255)
    position = models.IntegerField()  # 1st, 2nd, 3rd mention
    context = models.TextField(blank=True)  # Surrounding text
    
    # Competitors or main brand
    is_main_brand = models.BooleanField(default=False)
    competitor = models.ForeignKey(Competitor, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        ordering = ['position']
    
    def __str__(self):
        return f"{self.brand_name} at position {self.position}"


class SentimentScore(models.Model):
    """Sentiment analysis for each brand mention"""
    SENTIMENT_CHOICES = [
        ('very_positive', 'Very Positive'),
        ('positive', 'Positive'),
        ('neutral', 'Neutral'),
        ('negative', 'Negative'),
    ]
    
    SENTIMENT_WEIGHTS = {
        'very_positive': 1.2,
        'positive': 1.0,
        'neutral': 0.8,
        'negative': 0.5,
    }
    
    mention = models.OneToOneField(BrandMention, on_delete=models.CASCADE, related_name='sentiment')
    sentiment = models.CharField(max_length=20, choices=SENTIMENT_CHOICES)
    reasoning = models.TextField(blank=True)  # Why this sentiment
    confidence = models.FloatField(default=1.0)
    
    def get_weight(self):
        return self.SENTIMENT_WEIGHTS.get(self.sentiment, 0.8)
    
    def __str__(self):
        return f"{self.mention.brand_name} - {self.sentiment}"


class VisibilityScore(models.Model):
    """Aggregated visibility scores per brand"""
    project = models.ForeignKey(VisibilityProject, on_delete=models.CASCADE, related_name='visibility_scores')
    brand_name = models.CharField(max_length=255)
    is_main_brand = models.BooleanField(default=False)
    competitor = models.ForeignKey(Competitor, on_delete=models.SET_NULL, null=True, blank=True)
    
    # Component scores
    frequency_score = models.FloatField(default=0.0)  # 0-1
    prominence_score = models.FloatField(default=0.0)  # Average of 1/position
    sentiment_score = models.FloatField(default=0.0)  # Weighted average
    model_coverage_score = models.FloatField(default=0.0)  # Weighted by model importance
    
    # Final aggregated score
    raw_score = models.FloatField(default=0.0)
    normalized_score = models.FloatField(default=0.0)  # 0-100
    
    # Metadata
    total_mentions = models.IntegerField(default=0)
    prompts_appeared_in = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ['project', 'brand_name']
        ordering = ['-normalized_score']
    
    def __str__(self):
        return f"{self.brand_name} - {self.normalized_score:.1f}%"


class DetailedReport(models.Model):
    """Comprehensive analysis report"""
    project = models.OneToOneField(VisibilityProject, on_delete=models.CASCADE, related_name='report')
    
    # Report sections (JSON fields for flexibility)
    competitor_comparison = models.JSONField(default=dict)
    prompt_wise_analysis = models.JSONField(default=dict)
    model_wise_analysis = models.JSONField(default=dict)
    negative_sentiment_analysis = models.JSONField(default=dict)
    research_sources = models.JSONField(default=list)
    
    # Insights and recommendations
    why_competitors_win = models.TextField(blank=True)
    content_gaps = models.TextField(blank=True)
    messaging_gaps = models.TextField(blank=True)
    positioning_weaknesses = models.TextField(blank=True)
    
    # Action plan
    content_ideas = models.JSONField(default=list)
    seo_pr_recommendations = models.JSONField(default=list)
    messaging_improvements = models.JSONField(default=list)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Report for {self.project.company_name}"


class ExecutionLog(models.Model):
    """Track execution flow and errors"""
    LOG_LEVELS = [
        ('info', 'Info'),
        ('warning', 'Warning'),
        ('error', 'Error'),
    ]
    
    project = models.ForeignKey(VisibilityProject, on_delete=models.CASCADE, related_name='logs')
    level = models.CharField(max_length=10, choices=LOG_LEVELS, default='info')
    module = models.CharField(max_length=50)  # module1, module2, module3
    message = models.TextField()
    details = models.JSONField(default=dict, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['timestamp']
    
    def __str__(self):
        return f"[{self.level}] {self.module} - {self.message[:50]}"
